<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>THE ICON TURNS 20 | kojie.san</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #ffffffaf;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 600px;
            margin: 20px auto;
            background: #ffffffaf;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .header {
            background-color: #c40000;
            color: #ffffff;
            padding: 20px;
            text-align: center;
        }
        .content {
            padding: 20px;
        }
        .footer {
            background-color: #f4f4f9;
            color: #666;
            font-size: 12px;
            text-align: center;
            padding: 10px 20px;
        }
        .btn {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            color: #ffffff;
            background-color: #0073e6;
            text-decoration: none;
            border-radius: 5px;
            margin-top: 10px;
        }
        .btn:hover {
            background-color: #005bb5;
        }
        .stats {
            background-color: #f9f9f9;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
        }
        .stats h2 {
            color: #0073e6;
            font-size: 24px;
            margin-bottom: 10px;
        }
        .stats p {
            font-size: 18px;
            margin: 5px 0;
        }
        .stats-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        .stats-table th, .stats-table td {
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }
        .stats-table th {
            background-color: #f4f4f9;
            color: #0073e6;
        }
        .stats-table td {
            background-color: #f9f9f9;
        }
        .button {
            background-color: #001f3f; /* Theme button color */
            color:rgb(255, 255, 255) !important; /* Light text for contrast, !important for email clients */
            padding: 12px 25px; /* Adjusted padding */
            text-decoration: none;
            border-radius: 5px;
            display: inline-block;
            font-weight: 500;
            font-size: 16px;
            border: 1px solid #E7D8C0; /* Border matching the theme */
            transition: background-color 0.2s ease-in-out;
            margin: 0 5px; /* Add margin for spacing between buttons */
        }
        .button:hover {
            background-color:rgb(1, 64, 128); /* Darker shade of theme on hover */
            color: rgb(255, 255, 255) !important; /* Ensure hover text color also overrides defaults */
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <img src="{{ asset('/images/nobg20.png') }}" alt="turns20-logo" class="product-img" height="120" width="150">
            <h1>{{ config('app.name') }} NOTIFICATION</h1>
        </div>

        <div class="content">
            <div class="stats">
                <h3>
                    @if(isset($greeting) && !empty($greeting))
                        {{ $greeting }}
                    @endif
                </h3>
                <br>
                <p>
                    @foreach($introLines ?? [] as $line)
                        {!! $line !!}
                    @endforeach
                </p>
                <br>
                <br>
                    @foreach($outroLines ?? [] as $line)
                        <h3>{!! $line !!}</h3>
                    @endforeach
                <br>

                <p>Thank you, </p>
                <img src="{{ asset('/images/kojiesan.png') }}" alt="kojiesan-logo" class="product-img" height="100" width="100">

                <br>
                © {{ date('Y') }} BEVI Beauty Elements Ventures Inc. All rights reserved.
            </div>

            <p>This is an automated email generated by the system. Please do not reply.</p>
        </div>

        <div class="footer">
            <p>CONFIDENTIALITY NOTICE: This communication is intended solely for the individual(s) to whom it is addressed. This email, which includes any attachments, is confidential. If you are not the intended recipient of this communication, you may not disseminate, distribute, copy, or otherwise disclose or use the contents of this communication without the written authority of Beauty Elements Ventures, Inc. If you have received this communication in error, please delete and destroy all copies and kindly notify the IT Department by email or call them immediately. Thank you.</p>
        </div>
    </div>

</body>
</html>
